import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState, useEffect } from "react";
import Button from "./components/Button";
import FeedbackForm from "./components/FeedbackForm";
import FeedbackItem from "./components/FeedbackItem";
import axios from "axios";

export default function FeedbackPage() {
  const [feedbacks, setFeedbacks] = useState([]);

  useEffect(() => {
    //Promise
    axios.get("http://localhost:4000/feedbacks").then((x) => setFeedbacks(x.data));
    // cleanup unmount 처리
    return () => {
        console.log('unmount')
    }

  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
        <FeedbackForm />
        <Button variants="primary">button</Button>
        <Button variants="secondary">button</Button>
        {feedbacks.map((item) => (
          <FeedbackItem item={item} />
        ))}
      </main>
    </div>
  );
}
