import { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Card from "../components/Card";
import Button from "../components/Button";

//React routing 처리 - react-router
// next.js

export default function HomePage() {
  const [count, setCount] = useState(0);

  //렌더링이 된 후 실행
  // 의존성 array 전달
  useEffect(() => {
    console.log("render" + count);
  }, [count]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
        <Card>
          <div>Hello</div>
          <Button>테스트</Button>
          {count}
          <Button
            onClick={() => {
              setCount((c) => c + 1);
            }}
            variants="secondary"
          >
            secondary
          </Button>
        </Card>
        <Link href="/feedback">hello로 이동</Link>
      </main>
    </div>
  );
}
